In [10]:
# For a single neuron we have 3 inputs, 3 weights, and one bias
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2
# y = sum(inputs[i] * weights[i]) + bias | (i = 0 -> 2 in this case)

In [13]:
output = (inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + bias)

In [14]:
output

2.3

In [22]:
# adding a new previous neuron which adds a new input and weight
# still a single neuron with now 4 inputs, 4 weights, and one bias
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2
print(inputs)
print(weights)

[1.0, 2.0, 3.0, 2.5]
[0.2, 0.8, -0.5, 1.0]


In [23]:
output = (inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + inputs[3] * weights[3] + bias)

In [24]:
output

4.8

In [29]:
# Now a group (layer) of 3 neurons that had 4 inputs (whether training data or previous neurons from previous layer)
# All have the same inputs since each of them are connected to the previous ones / training data
inputs = [1.0, 2.0, 3.0, 2.5]
# 3 unique weights for each neuron
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

# 3 different unique biases for each neuron
bias1 = 2
bias2 = 3
bias3 = 0.5

In [30]:
# Outputs for all 3 neurons
outputs = [
    # Neuron 1
    inputs[0] * weights1[0] +
    inputs[1] * weights1[1] +
    inputs[2] * weights1[2] +
    inputs[3] * weights1[3] + bias1,

    # Neuron 2
    inputs[0] * weights2[0] +
    inputs[1] * weights2[1] +
    inputs[2] * weights2[2] +
    inputs[3] * weights2[3] + bias2,

    # Neuron 3
    inputs[0] * weights3[0] +
    inputs[1] * weights3[1] +
    inputs[2] * weights3[2] +
    inputs[3] * weights3[3] + bias3]

In [34]:
outputs

[4.8, 1.21, 2.385]

In [35]:
# Doing the same as before but without hard coding because the more neurons we have, the more work it would be
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

In [37]:
# getting output this way (layer_outputs)
layer_outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):

    # Zeroed output at start of this current neuron's iteration
    neuron_output = 0

    # For each input and weight to the neuron
    for n_input, weight in zip(inputs, neuron_weights):
        # Multiply input by weight and add to output
        neuron_output += n_input * weight
    # Add bias
    neuron_output += neuron_bias

    # Add this neuron's outputs to the layer_outputs array
    layer_outputs.append(neuron_output)

In [40]:
# Should be [4.8, 1.21, 2.385] if not, then probably ran above cell more than once
layer_outputs

[4.8, 1.21, 2.385]

In [1]:
# Lists vs Arrays vs Matrices vs Vectors vs Tensors
# This is a list, an array and a vector, and not matrix because not 2d
l = [1,5,6,2]

# list of lists, a matrix, not a vector, and a 2d array
lol = [[1,5,6,2],
       [3,2,1,3]]

# lists of lists of lists, a 3d array, not a vector, and not a matrix because not 2d
lolol = [[[1,5,6,2],
          [3,2,1,3]],
         [[5,2,1,2],
          [6,4,8,4]],
         [[2,8,5,3],
          [1,1,9,4]]]

# list of lists, not array because different lengths (not homologous), not a vector because not 1d, and not a matrix because not homologous
another_list_of_lists = [[4,2,3],
                         [5,1]]

# This is a list of lists, a 2d array, not a vector because not 1d, and a matrix because it is 2d
list_matrix_array = [[4,2],
                     [5,1],
                     [8,2]]

# Shape is (3, 2, 4): 3 because 3 elements (2d arrays) inside the outermost brackets, 2 because of 2 elements (1d arrays) per chunk
# from the previous elements, and 4 because 4 elements per single array per chunk per element
# [[1,5,6,2],
#  [3,2,1,3]]

# [[5,2,1,2],
#  [6,4,8,4]]

# [[2,8,5,3],
#  [1,1,9,4]]
lolol = [[[1,5,6,2],
          [3,2,1,3]],
         [[5,2,1,2],
          [6,4,8,4]],
         [[2,8,5,3],
          [1,1,9,4]]]


In [2]:
# Dot Product
# Vector a * Vector b = sum from i = 1 to n of a_i * b_i = a[1] * b[1] + a[2] * b[2] + ... + a[n] * b[n]

# Example:
# 2 vectors
a = [1,2,3]
b = [2,3,4]

# Calculate dot product in a rudimentary way
dot_product = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
print(f"Dot Product of vectors {a} and {b}: {dot_product}")

Dot Product of vectors [1, 2, 3] and [2, 3, 4]: 20


In [1]:
# Vector Addition
# Vector a + Vector b = Vector(a[1] + b[1], a[2] + b[2], a[n]+ b[n]) where n is the length of vectors a and b

# Example:
# 2 vectors
a = [1,2,3]
b = [2,3,4]

# Calculate vector addition in a rudimentary way
vector_add = [a[0] + b[0], a[1] + b[1], a[2] + b[2]]
print(f"Resulting vector after adding the two vectors {a} and {b} is: {vector_add}")

Resulting vector after adding the two vectors [1, 2, 3] and [2, 3, 4] is: [3, 5, 7]


In [2]:
# Starting to use numpy
import numpy as np

In [6]:
# For 1 neuron
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

outputs = np.dot(weights, inputs) + bias

print(outputs)

4.8


In [14]:
# For 3 neurons
# Doing the same calculation for 3 neurons as before but with numpy this time
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(weights, inputs) + biases

layer_outputs

array([4.8  , 1.21 , 2.385])

In [19]:
# Working with batches of inputs instead of one at a time
batch = [[1,5,6,2],
         [3,2,1,3],
         [5,2,1,2],
         [6,4,8,4],
         [2,8,5,3],
         [1,1,9,4],
         [6,6,0,4],
         [8,7,6,4]]

np.shape(batch)

(8, 4)

In [33]:
# Matrix Product
a = [[0.49,0.97,0.53,0.05],
     [0.33,0.65,0.62,0.51],
     [1.0,0.38,0.61,0.45],
     [0.74,0.27,0.64,0.17],
     [0.36,0.17,0.96,0.12]]

print(np.shape(a))

b = [[0.79,0.32,0.68,0.9,0.77],
     [0.18,0.39,0.12,0.93,0.09],
     [0.87,0.42,0.6,0.71,0.12],
     [0.45,0.55,0.4,0.78,0.81]]

print(np.shape(b))
print("")

# Perform Matrix Product

# a * b
c = np.dot(a, b)
print(c)
print(np.shape(c))

# b * a
c = np.dot(b, a)
print("")
print(c)
print(np.shape(c))

(5, 4)
(4, 5)

[[1.0453 0.7852 0.7876 1.7584 0.5687]
 [1.1466 0.9    0.8784 1.7395 0.8001]
 [1.5916 0.9719 1.2716 2.0375 1.2419]
 [1.2665 0.7044 0.9876 1.5041 0.8086]
 [1.2042 0.6507 0.8892 1.2573 0.5049]]
(5, 5)

[[2.1159 1.6066 2.3471 0.7541]
 [1.0575 0.7401 1.092  0.4308]
 [1.7335 1.557  1.6571 0.6628]
 [1.6708 1.2943 2.1003 0.7128]]
(4, 4)


In [50]:
# Matrix Product with a row vector and a column vector (matrices)

# Row vector
a = np.array([1,2,3])
a = np.atleast_2d(a)
print(a)
print(np.shape(a))

print("")

# Column vector
b = np.array([2,3,4])
b = np.atleast_2d(b).T
print(b)
print(np.shape(b))

print("")

c = np.dot(a, b)
print(c)
print(np.shape(c))

[[1 2 3]]
(1, 3)

[[2]
 [3]
 [4]]
(3, 1)

[[20]]
(1, 1)


In [56]:
# Transposition of matrices or vectors
a = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14],
              [15, 16, 17, 18, 19]])

a_T = a.T # transpose

print(a)
print(np.shape(a))

print("") 

print(a_T)
print(np.shape(a_T))

# What we see happen is that matrix a's left to right elements are now it's up to down elements
# Similarily, it's up to down elements are now its left to right elements
# If you see the order it used to be 0 1 2 3 4 in the first array in the outer array but now its 0 5 10 15 which was
# The up to down order from the array before being transposed

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
(5, 4)
