In [20]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
import matplotlib.pyplot as plt

%matplotlib inline
nnfs.init()

In [21]:
# getting inputs and getting the layer outputs for 1 layer then 2
# Had to set the lists to np arrays so it didn't mess up when importing nnfs
inputs = np.array([[1,2,3,2.5],
          [2.,5.,-1.,2.],
          [-1.5,2.7,3.3,-0.8]])
weights = np.array([[0.2,0.8,-0.5,1.],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]])
biases = np.array([2,3,0.5])

# Weights and biases for our 2nd layer of neurons
weights2 = np.array([[0.1,-0.14,0.5],
             [-0.5,0.12,-0.33],
             [-0.44,0.73,-0.13]])
biases2 = np.array([-1,2,-0.5])

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases

print(layer1_outputs)

print("")

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

print(layer2_outputs)

[[ 4.79999995  1.21000004  2.38499999]
 [ 8.9000001  -1.80999994  0.19999999]
 [ 1.41000003  1.051       0.02599999]]

[[ 0.50310004 -1.04184985 -2.03874993]
 [ 0.24339998 -2.73320007 -5.76329994]
 [-0.99314     1.41254002 -0.35655001]]


In [22]:
class Layer_Dense:

    def __init__(self, n_inputs, n_neurons):
        # Initialize weights and biases
        # pass # Using pass statement as a placeholder
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    # Forward pass
    def forward(self, inputs):
        # Calculate output values from inputs, weights and biases
        #pass # using pass statements as a placeholder
        self.output = np.dot(inputs, self.weights) + self.biases

In [23]:
# Makes an np array with random values with a shape of 2x5
print(np.random.randn(2,5))

[[ 1.7640524   0.4001572   0.978738    2.2408931   1.867558  ]
 [-0.9772779   0.95008844 -0.1513572  -0.10321885  0.41059852]]


In [24]:
# Example of what happens inside of our init in the Layer_Dense class

n_inputs = 2
n_neurons = 4
weights = 0.01 * np.random.randn(n_inputs, n_neurons)
biases = np.zeros((1, n_neurons))

print(weights)
print(biases)

[[ 0.00144044  0.01454273  0.00761038  0.00121675]
 [ 0.00443863  0.00333674  0.01494079 -0.00205158]]
[[0. 0. 0. 0.]]


In [25]:
# Creating dataset
X, Y = spiral_data(samples=100, classes=3)

# Create dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)

# Perform a forward pass of our training data through this layer
dense1.forward(X)

# Let's see the output of the first few samples:

print(dense1.output[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-7.5800526e-05  2.9739751e-05 -6.1969404e-05]
 [-6.7263041e-05  4.5470897e-05  4.2126936e-05]
 [-2.1008983e-04  4.8072201e-05 -3.4661393e-04]
 [-2.3864214e-04  4.2164596e-05 -4.5704172e-04]]
